- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1013
JIRA and PR's included in this release: 
CP-1015  - remove all non OSS dependencies  - https://github.com/Workiva/w_module/pull/31
CP-1019  - update inline doc strings, w_module  - https://github.com/Workiva/w_module/pull/32
CP-1020  - add license text, w_module  - https://github.com/Workiva/w_module/pull/33
CP-1026  - add README, w_module  - https://github.com/Workiva/w_module/pull/34
CP-1031  - fix page load reject in panel example  - https://github.com/Workiva/w_module/pull/35
CP-1044  - enable public CI, w_module  - https://github.com/Workiva/w_module/pull/36
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.0...CP-1013_release_0.3.1
> CP-1013 Release w_module 0.3.1

- example/panel/modules/hierarchy_module.dart
- lib/src/event.dart
- pubspec.yaml
- test/event_test.dart
- `dart_style` 0.2.1 is out with improved formatting
- Apply newest formatting
- Bump `dart_style` minimum version to 0.2.1
- n/a
- n/a
@trentgrover-wf
@maxwellpeterson-wf 
@dustinlessard-wf
@jayudey-wf
> CP-1166 Dart formatter updates for w_module, dart_style 0.2.1.

- lib/src/lifecycle_module.dart
- test/lifecycle_module_test.dart
[Jira Ticket](https://jira.atl.workiva.net/browse/REF-1068)
Lux uses a pattern whereby they add their components in an `onDidLoadChildModule` method that gets called automagically when a child module is loaded. This seems to work out very nicely and results in clean, easy-to-read code.
However, since we don't support this directly in the SDK or in w_module it is left up to consumers to implement the boilerplate and many consumers might not pick up on it unless they read the Lux source code. Additionally, and this is fairly minor, the only way to wire this up at the level of an Experience is to listen to the appropriate stream, which is slightly complex due to the need to cancel stream subscriptions.
I originally set out to add this method to the `Experience` in the wdesk_sdk repo, but it …
> REF-1068 Add additional lifecycle methods

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1184
JIRA and PR's included in this release: 
CP-1227  - cleanup old tooling, w_module  - https://github.com/Workiva/w_module/pull/45
CP-1335  - Add DeferredModule transformer, w_module.  - https://github.com/Workiva/w_module/pull/40
======= w_module 0.3.3 items =======
REF-1068  - Add onDidLoadChildModule and similar methods to LifecycleModule  - https://github.com/Workiva/w_module/pull/48
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.2...CP-1184_release_0.3.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.2...0.3.3
> CP-1184 Release w_module 0.3.3

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-2077
Releases that need to go out at the same time (if any): 
JIRA and PR's included in this release: 
======= w_module 0.3.4 items =======
CP-2083  - Remove deferred module transformer  - https://github.com/Workiva/w_module/pull/51
CP-2082  - Revert breaking change to LifecycleModule.name  - https://github.com/Workiva/w_module/pull/50
======= end =======
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.3...CP-2077_release_0.3.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.3...0.3.4
> CP-2077 Release w_module 0.3.4

- pubspec.yaml
* [CP-2089 Updated README to use Github raw content url](https://github.com/Workiva/w_module/pull/54)
* [REF-1267 Add suspend / resume semantics](https://github.com/Workiva/w_module/pull/55)
* [CP-2683 Enable strong-mode/linter. Use `@protected` annotation.](https://github.com/Workiva/w_module/pull/56)
Requested by: charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.4...version-bump-w_module-0-4-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.3.4...0.4.0
> CP-2084 Release w_module 0.4.0

- .travis.yml
- pubspec.yaml
- smithy.yaml
- We needed to add a smithy.yaml for release management to more easily track dependencies.
**Source:**
- Included smithy.yaml
**Tests:**
- n/a
- passing CI's
- passing CI
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf
@sebastianmalysa-wf
> CP-2941 Adding smithy.yaml

- pubspec.yaml
* [MOBILE-2277: Implement serializable w_module](https://github.com/Workiva/w_module/pull/59)
* [CP-2941 Adding smithy.yaml](https://github.com/Workiva/w_module/pull/60)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.4.0...version-bump-w_module-0-4-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.4.0...0.4.1
> CP-2762 Release w_module 0.4.1

- pubspec.yaml
* [RAP-1510 Use Enum Value in Noop Warning Message](https://github.com/Workiva/w_module/pull/66)
* [RAP-1482 Mix Disposable into LifecycleModule](https://github.com/Workiva/w_module/pull/62)
* [RAP-1483 Only allow one module load/unload cycle](https://github.com/Workiva/w_module/pull/63)
* [RAP-1484 Enforce LifecycleModule State Transitions](https://github.com/Workiva/w_module/pull/64)
* [RAP-1501 Implement Disposal Via Composition](https://github.com/Workiva/w_module/pull/65)
Requested by: @bencampbell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.4.1...version-bump-w_module-1-0-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/0.4.1...1.0.0
> CP-3023 Release w_module 1.0.0

- docs.yml
We would like this readme in the dev portal
Added docs.yml
previous major version
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp
> WP-3662 : added docs.yml

- pubspec.yaml
* [RAP-1529 Do not allow loadChildModule calls when unloading or unloaded](https://github.com/Workiva/w_module/pull/68)
* [RAP-1628 Create simple module API.](https://github.com/Workiva/w_module/pull/69)
* [WP-3662 : added docs.yml](https://github.com/Workiva/w_module/pull/70)
* [RAP-1679 Stream Lifecycle Method Errors](https://github.com/Workiva/w_module/pull/71)
Requested by: @jayudey-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.0.0...version-bump-w_module-1-1-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.0.0...1.1.0
> WP-3239 Release w_module 1.1.0

- pubspec.yaml
* [WP-3859 Make Events closable. Add EventsCollection base class.](https://github.com/Workiva/w_module/pull/73)
Requested by: @jayudey-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.1.0...version-bump-w_module-1-2-0_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.1.0...1.2.0
> WP-3736 Release w_module 1.2.0

- pubspec.yaml
* [RAP-1850 Await Loading, Suspending, and Resuming State Transitions](https://github.com/Workiva/w_module/pull/81)
Requested by: @bencampbell-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.1...version-bump-w_module-1-2-2_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.1...1.2.2
> WP-3905 Release w_module 1.2.2

- example/panel/panel_app.dart
- pubspec.yaml
**Jira Ticket:** [RAP-2010](https://jira.atl.workiva.net/browse/RAP-2010)
We should use platform_detect.
Replaced browser_detect usage with platform_detect.
> RAP-2010 Replace browser_detect usage with platform_detect

- pubspec.yaml
* [RAP-2010 Replace browser_detect usage with platform_detect](https://github.com/Workiva/w_module/pull/83)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.2...version-bump-w_module-1-2-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.2...1.2.3
> WP-4042 Release w_module 1.2.3

- pubspec.yaml
* [RAP-2055 Log LifecycleEvents](https://github.com/Workiva/w_module/pull/90)
* [RAP-2139 Ensure dispose is called when onUnload fails.](https://github.com/Workiva/w_module/pull/91)
Requested by: @trentgrover-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.5...version-bump-w_module-1-2-6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.5...1.2.6
> WP-4551 Release w_module 1.2.6

- pubspec.yaml
* [RAP-2220 Update Module to the latest DisposableManager interface](https://github.com/Workiva/w_module/pull/93)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.6...version-bump-w_module-1-3-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.6...1.3.0
> WP-4836 Release w_module 1.3.0

- pubspec.yaml
* [WP-4883 Ensure Examples and Tests run w/ DDC](https://github.com/Workiva/w_module/pull/99)
* [WP-4899 Make LifecycleModule a proper Disposable:](https://github.com/Workiva/w_module/pull/101)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.4.0...Workiva:release_w_module_1_5_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.4.0...1.5.0
> WP-4913 Release w_module 1.5.0

- CODEOWNERS
Add a `CODEOWNERS` file so that we can turn on the "require reviews from codeowners" option.
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
@Workiva/app-frameworks 
@Workiva/rich-app-platform-pp
> WP-5633 Add CODEOWNERS file

- lib/src/lifecycle_module.dart
- lib/src/serializable.dart
- test/lifecycle_module_test.dart
Rename loggers to follow the pattern: `<package_name>.<class_name>` per @leerobinson-wf's email to wf-dev.
@Workiva/app-frameworks
> WP-5746 w_module should follow new logger name standard

- pubspec.yaml
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/w_module/pull/109)
* [af-266 : log at finest](https://github.com/Workiva/w_module/pull/112)
* [AF-1961 Deprecate serializable_module.dart entry point](https://github.com/Workiva/w_module/pull/118)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.5.1...Workiva:release_w_module_1_5_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.5.1...1.5.2
> WP-5762 Release w_module 1.5.2

- pubspec.yaml
* [AF-1656 - Tracing for lifecycle transitions](https://github.com/Workiva/w_module/pull/114)
* [make activeSpan protected](https://github.com/Workiva/w_module/pull/122)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.5.2...Workiva:release_w_module_1_6_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.5.2...1.6.0
> AF-1979 Release w_module 1.6.0

- pubspec.yaml
* [AF-2560 module name in operation name](https://github.com/Workiva/w_module/pull/125)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.0...Workiva:release_2.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.0...2.0.1
> AF-2435 Release w_module 2.0.1

- lib/src/lifecycle_module.dart
- test/lifecycle_module_test.dart
Backpatch #125 into the 1.x version of w_module
> AF-2585 Operation name backpatch

- pubspec.yaml
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.1...Workiva:release_1.6.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.1...1.6.1
> AF-2594 Release w_module 1.6.1

- pubspec.yaml
* [AF-2735 memory leak with tracing](https://github.com/Workiva/w_module/pull/130)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.1...Workiva:release_w_module_2.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.1...2.0.2
> AF-2569 Release w_module 2.0.2

- lib/src/lifecycle_module.dart
- test/lifecycle_module_test.dart
Backpatch for https://github.com/Workiva/w_module/pull/130
See above PR
> AF-2757 Backpatch 2735

- pubspec.yaml
* [AF-2757 Backpatch 2735](https://github.com/Workiva/w_module/pull/131)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.2...Workiva:release_w_module_1.6.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.2...1.6.2
> AF-2753 Release w_module 1.6.2

- pubspec.yaml
* [AF-1540 AF-2674  consumer-specified timing for "first useful state"](https://github.com/Workiva/w_module/pull/115)
* [build cleanup](https://github.com/Workiva/w_module/pull/134)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.2...Workiva:release_w_module_2.0.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.2...2.0.3
> AF-2755 Release w_module 2.0.3

- pubspec.yaml
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.3...Workiva:release_w_module_2.0.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.3...2.0.4
> AF-2873 Release w_module 2.0.4

- .github/PULL_REQUEST_TEMPLATE.md
- CODEOWNERS
- CONTRIBUTING.md
- pubspec.yaml
- test/lifecycle_module_test.dart
Client Platform is refreshing our contributing instructions as a result of solidifying our internal CP Code Review
and PR Merging Team agreement.
You can view the Details in this RFD: https://docs.google.com/document/d/1zQ9gMMnQo3AyYQfCThCwB76aYpU3BMmqm1faD5EA8bU/edit
This PR aligns the CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md with the new agreement.
- Removes all existing potential variations of CONTRIBUTING, PULL_REQUEST_TEMPLATE, and CODEOWNERS.
- Adds standardized PULL_REQUEST_TEMPLATE.md and CONTRIBUTING.md
> CPLAT-3300: CP Code Review and PR Merging Team agreement update

- pubspec.yaml
* [Increase opentracing version for basictracer-dart changes](https://github.com/Workiva/w_module/pull/141)
* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/w_module/pull/142)
Requested by: @dustin.pauze
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.5...Workiva:release_w_module_2.0.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.5...2.0.6
> CPLAT-3488 Release w_module 2.0.6

- pubspec.yaml
* [Point out listenToStream usage with events in README](https://github.com/Workiva/w_module/pull/147)
* [CPLAT-5757: Add severe logging for callback errors](https://github.com/Workiva/w_module/pull/148)
Requested by: @georgelesica-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.6...Workiva:release_w_module_2.0.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.6...2.0.7
> CPLAT-5540 Release w_module 2.0.7

- lib/src/lifecycle_module.dart
It was brought to our attention by @laurameckley-wk that it might be helpful to have stack traces attached to a few more of the logs emitted by w_module in order to help track down the root cause of the corresponding warnings.
Add stack traces to logs in `LifecycleModule`.
Add additional context to logs emitted by `LifecycleModule`.
> CPLAT-6708: Add stack trace to more logs

- pubspec.yaml
* [CPLAT-6708: Add stack trace to more logs](https://github.com/Workiva/w_module/pull/151)
* [CPLAT-6710: Add missing module name override](https://github.com/Workiva/w_module/pull/152)
* [CPLAT-6851: Add disposable type name(s)](https://github.com/Workiva/w_module/pull/153)
Requested by: @olesiathoms-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.7...Workiva:release_w_module_2.0.8
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.7...2.0.8
> CPLAT-5758 Release w_module 2.0.8

- .travis.yml
- Dockerfile
- tool/dev.dart
We typically use w_module in web apps so it would be nice to confirm the code works properly when compiled using dart2js.
Updated CI to use dart2js when running the unit tests with Dart 2. I also simplified how we submit code coverage reports to codecov in the Dockerfile.
Use dart2js when running unit tests with Dart 2 in CI.
- Passing CI should be sufficient
[contributing-manual-testing]: https://github.com/Workiva/w_module/blob/master/CONTRIBUTING.md#ma …
> CPLAT-7110 Run the unit tests using dart2js in Dart 2

- pubspec.yaml
> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
Now that React 16 is part of Production Wdesk we are coming back through to clean up the transitional comments, and dependency ranges.
We're also taking this opportunity to give you a head start on consuming Component2 / UiComponent2!
> __For more details, see [the Component2 Wiki](https://wiki.atl.workiva.net/display/CP/What%27s+new+in+Component2).__
To summarize Component2 changes:
- Supports new lifecycle methods, allowing us to use Concurrent Mode in the future
- Slightly faster
- Improved dev experience
- Props/state show up in the React DevTools, and primitive values (strings, numbers, booleans) can …
> CPLAT-8210: Cleanup React 16 Transition

- pubspec.yaml
Requested by: @greglittlefield-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.13...Workiva:release_w_module_2.0.14
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.13...2.0.14
> Release w_module 2.0.14

- .travis.yml
- pubspec.yaml
Newer versions of `over_react` use extension methods which are not compatible with Dart versions below 2.7.
- Update CI to run on `2.7.2`
> Update CI to run on Dart 2.7.2

- pubspec.yaml
> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
React 17 was released at the end of October and came with some exciting benefits. For the full list, see the [ReactJS blog post](https://reactjs.org/blog/2020/10/20/react-v17.html).
For Workiva, upgrading so promptly is even more exciting because it:
1. supports our Material-UI (MUI) effort. [MUI will support React 17](https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#500-alpha15) in their next major release. This major is the one that Client Platform will use as the corner stone for the MUI effort. Therefore, to be compatible, Workiva should adopt React 17 as well.
1. helps with the …
> Preparations for React 17 compatibility

- skynet.yaml
Currently pipelines pass because we are just echoing tests run in github workflows which if those tests fail the pipeline will still pass and deploy the broken changes we would like to prevent the pipeline from releasing if the github workflow fails this adds a skynet check that looks to see if the workflow passes or not and fails the skynet run if the workflow fails.
Add skynet config that verifies that the github workflows run passes and fails the run if it doesn't it uses the script in this image: https://github.com/Workiva/skynet-images/pull/127
Update skynet config to fail if github workflow fails.
While we perform many automated checks …
> FW-60 Add skynet config to check github workflow status

- pubspec.yaml
* [Narrow dependency_validator range to avoid NNBD issue](https://github.com/Workiva/w_module/pull/192)
* [Update to latest image of github ci verifier](https://github.com/Workiva/w_module/pull/193)
* [Fix w_common v2 breaking changes](https://github.com/Workiva/w_module/pull/194)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.29...Workiva:release_w_module_2.0.30
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.29...2.0.30
This pull request can be recreated by clicking …
> RM-151504 Release w_module 2.0.30

- README.md
The `new` keyword now optional and Dart, and is usually omitted. Remove it from the boilerplate.
> Remove `new` from boilerplate

- pubspec.yaml
* [Remove `new` from boilerplate](https://github.com/Workiva/w_module/pull/196)
* [w_common v2 rollout - 1 of 2 raise max](https://github.com/Workiva/w_module/pull/198)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.30...Workiva:release_w_module_2.0.31
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.30...2.0.31
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=19 …
> RM-159768 Release w_module 2.0.31

- pubspec.yaml
* [w_common v2 rollout - 2 of 2 raise min](https://github.com/Workiva/w_module/pull/200)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.31...Workiva:release_w_module_2.0.32
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.31...2.0.32
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=201)
> RM-161863 Release w_module 2.0.32

- pubspec.yaml
* Minor changes:
* [Mockito 5](https://github.com/Workiva/w_module/pull/202)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.32...Workiva:release_w_module_2.1.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.32...2.1.0
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=203)
> RM-163289 Release w_module 2.1.0

- pubspec.yaml
* [Test Dart 2.18](https://github.com/Workiva/w_module/pull/204)
* [Upgrade to platform_detect 2](https://github.com/Workiva/w_module/pull/206)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.1.0...Workiva:release_w_module_2.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.1.0...2.1.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=207)
> RM-167476 Release w_module 2.1.1

- pubspec.yaml
* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/w_module/pull/208)
* [Pin mockito 5](https://github.com/Workiva/w_module/pull/210)
* [Prepare for dart_dev v4.0.0](https://github.com/Workiva/w_module/pull/211)
* [w_common v3 rollout - 1 of 2 raise max](https://github.com/Workiva/w_module/pull/212)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.1.1...Workiva:release_w_module_2.1.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.1.1...2.1.2
This pull request can be recreated by …
> RM-179050 Release w_module 2.1.2

- pubspec.yaml
* [Update dart dependencies](https://github.com/Workiva/w_module/pull/214)
* [Make example a subpackage and remove root deps](https://github.com/Workiva/w_module/pull/215)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.1.2...Workiva:release_w_module_2.1.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.1.2...2.1.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=216 …
> RM-188020 Release w_module 2.1.3

- pubspec.yaml
* [Update dev dependencies for analyzer 2](https://github.com/Workiva/w_module/pull/223)
* [Avoid meta 1.10.0 problem by unblocking analyzer 5](https://github.com/Workiva/w_module/pull/224)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.0...Workiva:release_w_module_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.0...3.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_modu …
> RM-208800 Release w_module 3.0.1

- pubspec.yaml
* [Avoid accessing private members of child modules](https://github.com/Workiva/w_module/pull/229)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.1...Workiva:release_w_module_3.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.1...3.0.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=230)
> RM-215542 Release w_module 3.0.2

- pubspec.yaml
* [Dart 2.19](https://github.com/Workiva/w_module/pull/232)
* [Allow react 7 and w_flux 3](https://github.com/Workiva/w_module/pull/234)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.2...Workiva:release_w_module_3.0.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.2...3.0.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=235)
> RM-215977 Release w_module 3.0.3

- pubspec.yaml
* [react 7 and w_flux 3 step 2](https://github.com/Workiva/w_module/pull/236)
* [w_flux Migration: Action class to ActionV2](https://github.com/Workiva/w_module/pull/237)
* [Ensure all child modules get unloaded](https://github.com/Workiva/w_module/pull/239)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.3...Workiva:release_w_module_3.0.4
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.3...3.0.4
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/543 …
> RM-223683 Release w_module 3.0.4

- pubspec.yaml
* [Dispose modules during onLoad if parent is unloaded/unloading](https://github.com/Workiva/w_module/pull/243)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.5...Workiva:release_w_module_3.0.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.5...3.0.6
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=244)
> RM-244216 Release w_module 3.0.6

- pubspec.yaml
* [FEDX-697 : GHA OSS changes](https://github.com/Workiva/w_module/pull/248)
* [Replace mockito with mocktail](https://github.com/Workiva/w_module/pull/249)
* [FEA-3688 Update onResume type](https://github.com/Workiva/w_module/pull/250)
* [FEDX-1480: implemented reusable workflows](https://github.com/Workiva/w_module/pull/251)
* [FEDX-1707: Workiva Analysis Options v2](https://github.com/Workiva/w_module/pull/254)
* [Raise the build_web_compilers dependency max to v5.0.0](https://github.com/Workiva/w_module/pull/257)
* [Raise the meta dependency min to v1.16.0](https://github.com/Workiva/w_module/pull/259)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/w_module/pull/260)
Diff Between Last Tag and …
> RM-251055 Release w_module 3.0.8
