Workiva/w_module

lib/src/lifecycle_module.dart

- tests now fail in Dart 1.13 because the stream events don't seem to arrive in the expected order
**Source:**
- swapped async/await syntax for completers
- alternative option to @jayudey-wf 's PR here: https://github.com/Workiva/w_module/pull/39
**Tests:**
- no changes necessary
@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf
FYI @timmccall-wf

CP-1162 Use completers instead of async/await so tests work in Dart 1.13

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

It would be helpful to have a getter to access the `_childModules` list that is maintained by the `LifecycleModule`. Specifically, as someone who is extending the `LifecycleModule` it would be nice to not have to maintain my own list of child modules when it's already being managed by the parent class.
Added a getter that exposes the `_childModules` list as an `Iterable<LifecycleModule>`.
None -- this is just the introduction of a getter property for an existing field.

CP-1174 Add Child Modules Getter to LifecycleModule

---

pubspec.yaml

JIRA: https://jira.webfilings.com/browse/CP-1047
JIRA and PR's included in this release: 
CP-1162  - Use completers instead of async/await so tests work in Dart 1.13  - https://github.com/Workiva/w_module/pull/41
CP-1166  - Dart formatter updates for w_module, dart_style 0.2.1.  - https://github.com/Workiva/w_module/pull/42
CP-1174  - Add Child Modules Getter to LifecycleModule  - https://github.com/Workiva/w_module/pull/38
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/0.3.1...CP-1047_release_0.3.2

CP-1047 Release w_module 0.3.2

---

example/deferred/counter_module.dart
example/deferred/counter_module_abstracts.dart
example/deferred/deferred_counter_module.dart
example/deferred/index.dart
example/deferred/index.html
example/deferred/pair.dart
example/index.html
lib/alpha.dart
lib/alpha/annotations.dart
lib/alpha/annotations/deferrable_module.dart
lib/alpha/annotations/deferrable_module_api.dart
lib/alpha/annotations/deferrable_module_events.dart
lib/alpha/annotations/deferred_module.dart
lib/alpha/deferred_module_transformer.dart
lib/src/lifecycle_module.dart
lib/w_module.dart
pubspec.yaml
tool/dev.dart

- Need a way to create deferred versions of modules with as little effort as possible and without the need to recreate the deferred module loading logic in the module lifecycle.
**Source:**
- Use a pub transformer to generate the deferred module implementation.
- Generates getters for API, Components, and Events
- The API is wrapped such that any calls to the API triggers the loading of the module (if not already loaded). If the targeted API method is async or if the getter returned a Future, it will be proxied to the real module API once loaded. If it is sync, it will throw if the module had not yet been loaded.
- The Events are all proxied to allow listener registration immediately.
- The Components are wrapped but will throw if the module has not yet been loaded. Components that need …

CP-1335 Add DeferredModule transformer, w_module.

---

lib/src/lifecycle_module.dart

The deferred module PR that was merged a while back (#40) inadvertently introduced a breaking change by changing `LifecycleModule.name` from a property to a getter. Any module using the `name` setter would be affected by this.
Revert to property so that it has a setter and getter.
_Long term, I think it makes more sense for it to just be a getter (consumers should override the getter instead of setting the value elsewhere), but we'll have to do that in a proper breaking change release._
@trentgrover-wf 
@maxwellpeterson-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf 
@srinivasdhanwada-wf

CP-2082 Revert breaking change to LifecycleModule.name

---

README.md

This way it also shows on pub: https://pub.dartlang.org/packages/w_module
(Requires a pushing a +N version bump on pub, eg 0.3.4+1, for it to show)

CP-2089 Updated README to use Github raw content url

---

README.md
lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

We need some concept of suspend / resume for other projects. It seems to make sense to add it here, at the lowest level.
Add it. I added a few new bits:
* `isLoaded` - whether the module is loaded, if they're allowed to be toggled, this seems like a good idea
* `isSuspended` - this can be toggled, so it's nice to have a getter
* `onSuspend` - called when we suspend
* `onResume` - called when we resume
* `willSuspend`, `didSuspend` - dispatched before and after we suspend
* `willResume`, `didResume` - dispatched before and after we resume
I also added a `Logger` and added warnings in the following cases:
* Loading an already-loaded module
* Unloading a modules that has already been unloaded or was never loaded to begin with
* Suspending an already-suspended module
* Suspending a module …

REF-1267 Add suspend / resume semantics

---

analysis_options.yaml
example/panel/modules/basic_module.dart
example/panel/modules/data_load_async_module.dart
example/panel/modules/data_load_blocking_module.dart
example/panel/modules/deferred_heavy_lifter_implementation.dart
example/panel/modules/deferred_heavy_lifter_interface.dart
example/panel/modules/deferred_module.dart
example/panel/modules/flux_module.dart
example/panel/modules/hierarchy_module.dart
example/panel/modules/lifecycle_echo_module.dart
example/panel/modules/panel_module.dart
example/panel/modules/reject_module.dart
example/panel/panel_app.dart
example/random_color/random_color.dart
lib/src/event.dart
lib/src/lifecycle_module.dart
lib/src/module.dart
pubspec.yaml
test/lifecycle_module_test.dart
tool/dev.dart

The `meta` package has a `@protected` annotation that we can leverage to mark certain public class methods as callable only by instances of said class. This will be useful for our `onEvent()` methods that are expected to be overridden by subclasses of `Module` in order to respond to a particular event since they should only be called by the internal module logic and not by consumers of the module.
- Add `@protected` annotation to:
- `loadChildModule()`
- `onWillLoadChildModule()`
- `onDidLoadChildModule()`
- `onWillUnloadChildModule()`
- `onDidUnloadChildModule()`
- `onLoad()`
- `onShouldUnload()`
- `onUnload()`
> Caveat: When a subclass overrides a `@protected` method, they too will have to add the `@protected` annotation to their override in order for the analyzer to enforce the …

CP-2683 Enable strong-mode/linter. Use `@protected` annotation.

---

lib/serializable_module.dart
lib/src/module.dart
lib/src/serializable.dart
pubspec.yaml
test/serializable_test.dart
tool/dev.dart

- Added a way to serialize w_modules to allow for communication with other systems (such as a mobile app)
- A separate entry point for a serializable module so all the existing w_module logic does not have any browser specific dependencies.
- Added a `SerializableBus` singleton that registers for events and listens for api calls to modules
- Added a `SerializableModule` class that extends the existing `Module` class that adds needed information to serialize a module
- Added a `Reflectable` class that allows classes and methods to be reflected upon using mirrors.
- Added a `SerializableEvent` and `SerializableEvents` class that allows events to be serializable.
- Unit tests around additions and changes.
Please review: @trentgrover-wf @evanweible-wf @maxwellpeterson-wf 
An actual …

MOBILE-2277: Implement serializable w_module

---

lib/src/lifecycle_module.dart
lib/src/serializable.dart
pubspec.yaml
test/event_test.dart
test/lifecycle_module_test.dart

**Jira Ticket:** [RAP-1482](https://jira.atl.workiva.net/browse/RAP-1482)
We'd like to use `Disposable` in the `LifecycleModule`. This will allow us to properly close the stream controllers that it manages.
1. Mixed in `Disposable`.
1. Aliased `dispose` to `unload` and marked it `@deprecated`. This will help us guide consumers to rely on `unload` instead.
1. Overrode `onDispose` and documented it as deprecated as well.
**Note:** there will be at least two more PRs to follow: one to enforce a single load/unload cycle; and another to make load, unload, suspend, and resume noops when the module is already in the correct state.
@Workiva/rich-app-platform-pp 
@Workiva/web-platform-pp

RAP-1482 Mix Disposable into LifecycleModule

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

**Jira Ticket:** [RAP-1483](https://jira.atl.workiva.net/browse/RAP-1483)
We've decided to only allow one load/unload cycle for a module.
Updated `LifecycleModule.load` to check to see if the module has been through a load/unload cycle before. If it has been, then it now throws a `StateError`.

RAP-1483 Only allow one module load/unload cycle

---

README.md
lib/src/lifecycle_module.dart
lib/w_module.dart
test/event_test.dart
test/lifecycle_module_test.dart
test/module_test.dart
test/serializable_test.dart

**Jira Ticket:** [RAP-1484](https://jira.atl.workiva.net/browse/RAP-1484)
We should enforce proper transitions between `LifecycleModule` states. The arrows in the following diagram identify valid state transitions. Green arrows represent transitions that will proceed as requested. Blue arrows represent noops.
Updated `LifecycleModule` to enforce the valid transitions. If a transition will be a noop, log a warning. If an invalid transition is requested a `StateError` is thrown.

RAP-1484 Enforce LifecycleModule State Transitions

---

lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

Problem
---
Disposal of a `LifecycleModule` has been encapsulated as part of the `unload` lifecycle call. In order to provide the disposable management functions to child classes `LifecycleModule` was force to mixin `Disposable` and add deprecated aliases to the 'dispose' and 'onDispose' methods to 'unload' and 'onUnload' respectively. This extends the API of `LifecycleModule` in an inappropriate way that may confuse consumers. In addition, a `LifecycleModule` may be inadvertently maintained in a collection of `Disposable`s or managed by another `Disposable`.
Solution
---
Utilize the `DisposableManager` interface to define the disposable management API for a `LifecycleModule` without having to implement 'dispose' and `onDispose`. Calls to these management functions are proxied to an …

RAP-1501 Implement Disposal Via Composition

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

Problem
---
The utility function for pretty printing a `LifecycleState` enumeration value is incorrect and returns the left half of the enumeration value, id "LifecycleState.loaded => LifecycleState".
Solution
---
Return the correct portion of the split of a given enumeration.
Tests
---
- Updated tests to confirm warn statement contains the correct values.
Howto QA/+10
---
References
---
- /fya @Workiva/rich-app-platform-pp @Workiva/web-platform-pp

RAP-1510 Use Enum Value in Noop Warning Message

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

Problem
---
If a module attempts to load a child module while unloading or unloading it may be possible for internal event stream controllers to be added to after they have been closed. This returns an unxepcted exception which may be confusing for consumers.
Solution
---
By making calls to loadChildModule when a module is unloaded or unloading throw a state error indicating it is not allowed consumers better understand the failure.
Howto QA/+10
---
References
---
- /fya @Workiva/rich-app-platform-pp @Workiva/web-platform-pp

RAP-1529 Do not allow loadChildModule calls when unloading or unloaded

---

README.md
lib/src/lifecycle_module.dart
lib/src/simple_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

It is not possible for subscribers of lifecycle events to be aware of errors returned by the associated lifecycle method. For instance, an object may listen to the onUnload event in order to cleanup its state with respect to the a given module. If that module throws during `onLoad` the parent object would never receive the didUnload event and would maintain state related to the given module indefinitely. Consumers of a LifecycleModule should be able to react to errors thrown during lifecycle methods.
Capture all errors returned by the lifecycle methods and add them to the corresponding lifecycle stream. This allows consumers of a module to listen to a lifecycle stream and provide an `onError` handler which allows them to deal with the error in their own special way. If an `onError` is not …

RAP-1679 Stream Lifecycle Method Errors

---

pubspec.yaml

#73 added a dependency on code from the latest w_common (1.4.0) but I didn't correctly raise the lower bound.
Raise the lower bound of w_common to 1.4.0 so that a `pub get` with the latest w_module also pulls in the correct version of w_common.
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

WP-3897 Bump lower bound on w_common dependency

---

pubspec.yaml

* [WP-3897 Bump lower bound on w_common dependency](https://github.com/Workiva/w_module/pull/78)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.0...version-bump-w_module-1-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.0...1.2.1

WP-3864 Release w_module 1.2.1

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

The current implementation does not allow state transitions to occur while a transition is in progress. For instance, a consumer cannot call suspend and unload synchronously as unloading is not allowed when a module is suspending. Unloading **is** valid when a module is suspended though. If a consumer fails to await the suspend, the LifecycleModule should wait for the transition to complete and then proceed to unload.
Any transitioning state that is resolving to a valid state should be awaited in the event of a state change. For example, if a consumer `suspend`s and `unload`s in the same synchronous block, the unload should await the completion of the suspension before proceeding. The state of the module changes from isSuspending  to isUnloading so subsequent state changes must respect …

RAP-1850 Await Loading, Suspending, and Resuming State Transitions

---

analysis_options.yaml
test/serializable_test.dart

The `close_sinks` and `cancel_subscriptions` lints were not enabled. When I enabled them, I found a group of tests where `StreamController`s were never closed.
- Enable them.
- Close the offending controllers in the tests.

WP-4435 Add lints and close controllers.

---

lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

[Jira Ticket](https://jira.atl.workiva.net/browse/RAP-2057)
A bug was reported by @josephelliot-wk in which LifecycleModule throws if an unload was attempted and rejected because a child module returned false from its shouldUnload method.
The problem is that we are leaving the module in the unloading state after a rejected unload when we should probably be moving it back into the loaded state (or not moving it to unloading until after the shouldUnload check has passed).
Ensure that the state is reset to its previous state if the unload is rejected. We have to do this in the async `_unload` to keep the semantics the same as they were previously (transition to unloading happens immediately).
I updated one of the tests to guard against regressions.
State changes. These are well tested.
Added …

RAP-2057 Fix double unload bug

---

lib/src/lifecycle_module.dart

[Jira Ticket](https://jira.atl.workiva.net/browse/HY-4995)
Problem
--------
If a child module fails to load, references will be maintained to its subscriptions, even though they've been cancelled.
Solution
--------
Clean up references.
Potential Regressions
--------
Potential impact in handling when child module fails to load.
Tests
--------
None added.
QA / +10
--------

HY-4995 Clean up resources on failure to load

---

pubspec.yaml

* [RAP-2057 Fix double unload bug](https://github.com/Workiva/w_module/pull/86)
* [WP-4435 Add lints and close controllers.](https://github.com/Workiva/w_module/pull/87)
* [HY-4995 Clean up resources on failure to load](https://github.com/Workiva/w_module/pull/88)
Requested by: @todbachman-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.2.4...version-bump-w_module-1-2-5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.2.4...1.2.5

WP-4291 Release w_module 1.2.5

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart
test/utils.dart
tool/dev.dart

There is no insight into the current lifecycle state for a instance of LifecycleModule. 
Emit a log event when a `LifecycleModule` transitions to a new lifecycle state. This provides a consistent and clear indication of what state any given LifecycleModule instance is in.
- Explicit unit tests were added to confirm behavior
/fya @Workiva/rich-app-platform-pp @Workiva/web-platform-pp

RAP-2055 Log LifecycleEvents

---

lib/src/lifecycle_module.dart

The call to the internal disposable proxy is made after `onUnload`. If an error is returned by `onUnload`, this dispose call is never made leaking all instances retained by `Disposable`.
Dispose `_disposableProxy` in the `onUnload` error catch block.
@Workiva/rich-app-platform-pp

RAP-2139 Ensure dispose is called when onUnload fails.

---

lib/src/events_collection.dart
lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

`LifecycleModule` supports memory management by proxying to an underlying disposable instead of extending `Disposable` directly. It is currently implementing V3 but the latest version is V5.
Update `LifecycleModule` to update the latest version of the disposable manager interface: `DisposableManagerV5`.
> It would be nice if there was a `w_common_tests` package that provided a test suite that exercises classes that implement the `DisposableManager` interfaces so that we could get these verifications for free.
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

RAP-2220 Update Module to the latest DisposableManager interface

---

lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

There is a new version of the `DisposableManager` interface that we can update `LifecycleModule` to.
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

WP-4910 Update LifecycleModule to DisposableManagerV6

---

pubspec.yaml

* [WP-4910 Update LifecycleModule to DisposableManagerV6](https://github.com/Workiva/w_module/pull/96)
Requested by: @jayudey-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.3.0...version-bump-w_module-1-4-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.3.0...1.4.0

WP-4849 Release w_module 1.4.0

---

example/panel/index.html
example/panel/panel_app.dart
example/random_color/index.html
example/random_color/random_color.dart
lib/src/serializable.dart
pubspec.yaml
smithy.yaml
test/serializable_test.dart

w_module has not been updated to run with DDC
Update w_module to be DDC compliant!
- Updated version constraints on `w_flux` and `react` to pull in DDC compliant verions
- Updated examples to compile with DDC
- Addressed test failures when using DDC
- Addressed deprecations
@Workiva/web-platform-pp

WP-4883 Ensure Examples and Tests run w/ DDC

---

README.md
lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart

- `LifecycleModule` now extends `Disposable` instead of implementing the `DisposableManager` interface
- When unload() succeeds, the instance is also disposed
- When dispose() is called, it attempts to unload the module first, and then forces disposal regardless of the outcome of the unload step
- Prevents calls to all API methods after disposal has started
@Workiva/web-platform-pp @Workiva/rich-app-platform-pp

WP-4899 Make LifecycleModule a proper Disposable:

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

If a module has an uncaught exception during an error, it is impossible to unload because it is in the middle of a transition.
Specifically revert state back if a transition fails and clear the `_transition` completer so that the error that caused the transition to fail is not repeatedly consumed on subsequent `unload()` calls.

WP-4919 Unblock mid-transition states

---

pubspec.yaml

* [WP-4919 Unblock mid-transition states](https://github.com/Workiva/w_module/pull/103)
* [WP-5633 Add CODEOWNERS file](https://github.com/Workiva/w_module/pull/105)
* [WP-5746 w_module should follow new logger name standard](https://github.com/Workiva/w_module/pull/106)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/1.5.0...Workiva:release_w_module_1_5_1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/1.5.0...1.5.1

WP-5419 Release w_module 1.5.1

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

We're jamming up our browser console with info-logs.  From the discussion on https://docs.google.com/document/d/1Qsn333r3i92qTLVW7Lp2IHU7m5YAUh7kOWNOYLliul4/edit?ts=5af3033e#
It seemed like a good idea to move these logs down one level of logging severity.
Logs emitted by this library are at 'finest' level.  Exceptions continue to be logged as warnings.

af-266 : log at finest

---

.travis.yml
lib/serializable_module.dart

The `serializable_module.dart` entry point needs to be removed for Dart 2 compatibility. That will happen in a major release, which means we need to deprecate it in our current major line first.
@Workiva/app-frameworks 
@robbecker-wf

AF-1961 Deprecate serializable_module.dart entry point

---

example/panel/modules/sample_tracer.dart
example/panel/panel_app.dart
lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart
test/test_tracer.dart

Pretty much every module could benefit from added tracing, especially if it comes free to consumers.
- If a `globalTracer()` is configured for the application, create a span for each of the lifecycle transitions and expose it to consumers who may wish to apply additional tags or use it for `childOf` and `followsFrom` references to other tags.
- Pass on the `SpanContext` from the transition span to any child modules so their transitions have a `childOf` link back to this one.
Play with the example and note the console logging.

AF-1656 - Tracing for lifecycle transitions

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

This isn't helpful:
Put the module name in the operation name

AF-2560 module name in operation name

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

`_activeSpan` was being retained in memory after modules were unloaded.
First, use the wdesk_sdk examples without this branch to reproduce the memory leak issue.
1. Starting from the main examples page, open up an example document and then close it.
2. Watch the network tab. There will be 3 `tracing/` requests. (The period is 30 seconds so if it's been longer than that since the last `tracing/` request it's probably failed)
3. Manually garbage collect and then record a heap with sourcemaps (default behavior for me in Chrome without incognito). Search for `span` (or `Wspan`, etc)
Now point wdesk_sdk to use this branch and try again. After the third `tracing/` request, you shouldn't see any Wspans.
fyi @Workiva/app-frameworks

AF-2735 memory leak with tracing

---

Dockerfile

- run with official dart image
- install chrome
- remove xfvd screen instantiation.. unneeded for specified test runtime
Testing:
- ensure CI passes
@toddbeckman-wf @Workiva/app-frameworks @chrisgustavsen-wf @jeffhall-wk @bradbenjamin-wf

build cleanup

---

.travis.yml
Dockerfile
example/panel/index.html
example/panel/modules/data_load_async_module.dart
example/panel/modules/flux_module.dart
example/panel/modules/hierarchy_module.dart
example/panel/modules/panel_module.dart
example/panel/modules/reject_module.dart
example/panel/modules/sample_tracer.dart
example/random_color/index.html
example/random_color/random_color.dart
lib/src/lifecycle_module.dart
pubspec.yaml
test/lifecycle_module_test.dart
test/test_tracer.dart

Updates are needed to use this library under Dart 2
- updated analysis options and renamed to the proper name
- updated dependencies and dart sdk ranges in pubspec.yaml
- unit tests fixed for dart 2.
- fixed some type errors in the examples
- CI now enforces dartfmt under dart 2

AF-2971 Dart 2 compatibility

---

lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

We're seeing modules get leaking text_doc_client.
We think that clearing the list of modules is a fail-safe solution to ensure that we don't retain references to children modules when we've been disposed.
@jacobjohnson-wf @evanweible-wf @bencampbell-wf

Clear child modules on dispose.

---

CHANGELOG.md
pubspec.yaml

* [Clear child modules on dispose.](https://github.com/Workiva/w_module/pull/139)
Requested by: @greg.littlefield
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/2.0.4...Workiva:release_w_module_2.0.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/2.0.4...2.0.5

AF-3155 Release w_module 2.0.5

---

.travis.yml
Dockerfile
example/panel/modules/sample_tracer.dart
pubspec.yaml
test/test_tracer.dart

With version `1.1.0` of basictracer-dart, the opentracing version was increased to `1.0.0`. To prevent dependency conflicts, increase w_module's version to accommodate the changes.
@Workiva/app-frameworks

Increase opentracing version for basictracer-dart changes

---

README.md

In general we prefer `listenToStream` as opposed to `listen` with events, so I added a section of the README that describes how to do this.
Simple README update with example.

Point out listenToStream usage with events in README

---

.gitignore
lib/src/events_collection.dart
lib/src/lifecycle_module.dart
pubspec.yaml
test/events_collection_test.dart
test/lifecycle_module_test.dart

Some of the classes that extend or mixin `Disposable` missing `disposableTypeName` override.
This PR will add missing overrides, where it's necessary

CPLAT-6851: Add disposable type name(s)

---

example/panel/panel_app.dart
example/random_color/random_color.dart
pubspec.yaml

> __These changes / builds will first be reviewed by a member of the Client Platform team.__ 
> 
> Repo owners will be notified when it is ready for additional review, merge and release.
Wdesk is currently using ReactJS `15.6.1` _(released on June 14, 2017)_, and the Client Platform team 
has been working to upgrade our Dart wrappers to be compatible with the latest major version of ReactJS (`16.x`). 
Now that major releases of the `react` (`5.0.0`) and `over_react` (`3.0.0`) packages have laid the foundation
for ReactJS 16 compatibility, __its time to begin making the entire Workiva front-end
ecosystem compatible!__
__But Why?__
The ReactJS `16.0.0` release included an internal rewrite that set the stage for some new features, 
ranging from new and improved APIs for authoring UI, to a …

CPLAT-7616: Preparations for React 16 compatibility

---

lib/src/lifecycle_module.dart

Some `Future.error`s were missing stack traces, which resulted in no stack traces getting logged.
Add stack traces manually
I attempted to use async functions to do this (see https://github.com/Workiva/w_module/pull/165), but it ended up introducing subtle timing changes, which seemed too risky.
- Fix missing stacktraces in most StateErrors thrown by LifecycleModule
[contributing-manual-testing]: …

Add missing stack traces to Future.errors

---

pubspec.yaml

In order to enable Workiva to transition to Dart >=2.9.0 with ease, a slight update to OverReact factory syntax
is required.
__Important:__
1. Remember to update your snippets in order to prevent accidental regressions in boilerplate. [Here](https://github.com/Workiva/over_react/blob/master/snippets/README.md)
is the reference for OverReact snippets.
1. To prevent incompatible boilerplate from being introduced, a react-boilerplate core-check has been activated. This
core check will fail if the incompatible mixin based boilerplate is introduced again to a project that has migrated already.
> For more information on why this migration is important, see [this wiki update](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=182026853).
__NOTE:__ Only the mixin based boilerplate …

Update OverReact syntax to support Dart 2.9+

---

lib/src/lifecycle_module.dart

[this query](https://splunk.workiva.net/en-US/app/search/search?q=search%20index%3Dkinesis-harbour-prod%20source%3Dapp-int-collection-gateway%20%22PresenceModule%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-24h%40h&latest=now&sid=1631799547.277575_E1E254A8-D1AC-4B03-A4B7-AB2DD555FC19) shows that something is flooding prod with this warning:
> .suspend() was called while Module "PresenceModule" is already suspended; this is a no-op. Check for any unnecessary calls to .suspend().
We don't need to log like crazy for a no-op action, even if it is something we want to "warn" consumers about.
Lower the log severity of no-op calls to suspend. …

Lower log level of no-op

---

docs.yml

https://jira.atl.workiva.net/browse/DE-552
As part of, 
[Dev Portal Service deprecation](https://wiki.atl.workiva.net/display/DE/Poster+-+Dev+Portal+Discovery+2.0%3A+Discovery+and+Planning); 
we are deprecating the “docs.yml” file that’s been created to render repo markdown files on to the portal.
File paths included in docs.yml of this repo will no longer be rendered/hosted on
[Dev Portal](https://dev.workiva.net/docs/) with the yml file deletion.
Please reach out to `#support-dev-portal` or `#support-developer-efficiency` with any questions.
[_Created by Sourcegraph batch change `Workiva/remove_docs_yml`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_docs_yml)

DE-685: Delete docs.yml file created for Dev Portal.

---

skynet.yaml

Currently the skynet config is running on pull requests as well as releases which is causing us to hit the github api rate limit, we don't really need to have the skynet config running on pull requests because it's just needed for release pipelines. 
Add a run config to skynet that limits running to just releases and if there are changes to the skynet.yaml
Run skynet only on releases
[contributing-manual-testing]: …

FW-164 Only run skynet config on releases

---

.github/workflows/dart_ci.yml
lib/src/lifecycle_module.dart

w_common has a number of deprecations that are removed in v2. This batch attempts to
fix as many of the breaking changes as possible to prepare to move to v2.
Breaking Changes: https://github.com/Workiva/w_common/blob/master/w_common/CHANGELOG.md#200
[_Created by Sourcegraph batch change `Workiva/fix_w_common_v2_breaking_changes`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/fix_w_common_v2_breaking_changes)

Fix w_common v2 breaking changes

---

pubspec.yaml

Summary
---
Frontend Frameworks is updating dependencies! More details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This update will allow w_common 2x by raising the max to < 3.0.0
It also raises the minimum of a few packages that addressed w_common
v2 breaking changes. In order to be compatible with w_common v2, we
need at least these versions.
dart_dev_workiva 1.5.9
wdesk_sdk 3.7.8
w_router 1.1.15
w_flux 2.10.21
w_module 2.0.30
bigsky_rest_files 1.33.10
In addition, sass compilation was moved out of w_common into a 
w_common_tools package, so if it detects that the repo might need it, 
it might add a dependency on w_common_tools.
Lastly, app/pubspec.lock files may have needed to be updated to get 
those minimum versions of packages
For more info, reach out to …

w_common v2 rollout - 1 of 2 raise max

---

.github/workflows/dart_ci.yml
Dockerfile
tool/dart_dev/config.dart

Summary
---
This batch overrides the docker images used to equivalent Dart 2.18 versions.
The goal is to run as many CI runs across the dart ecosystem as possible on 
Dart 2.18 to find and fix errors before releasing a production 2.18 image.
[_Created by Sourcegraph batch change `Workiva/test_dart_218`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/test_dart_218)

Test Dart 2.18

---

pubspec.yaml

Summary
---
Frontend Frameworks is updating dependencies! More details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This will raise the max allowed version of platform_detect to allow v2.
[_Created by Sourcegraph batch change `Workiva/platform_detect_2_raise_max`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/platform_detect_2_raise_max)

Upgrade to platform_detect 2

---

example/pubspec.yaml
pubspec.yaml

Summary
---
Frontend Frameworks is updating dependencies! Now that we can resolve to analyzer 2
we can raise the minimums of many dependencies were ranged to support both 
analyzer 1 and 2.
```
pubspec_codemod raise-min analyzer 2.0.0 --recursive
pubspec_codemod raise-min dependency_validator 3.0.0 --recursive
pubspec_codemod raise-min test_html_builder 3.0.0 --recursive
pubspec_codemod raise-min dart_style 2.0.0 --recursive
pubspec_codemod raise-min build_web_compilers 3.0.0 --recursive
pubspec_codemod raise-min build_test 2.0.0 --recursive
pubspec_codemod raise-min build_runner 2.0.0 --recursive
pubspec_codemod raise-min w_common 3.0.0 --recursive
pubspec_codemod raise-min w_common_tools 3.0.0 --recursive
pubspec_codemod raise-min uuid 3.0.0 --recursive
pubspec_codemod raise-min fluri …
```

Update dev dependencies for analyzer 2

---

example/pubspec.yaml
pubspec.yaml

Summary
---
This is a batch change to apply a dependency range pin to the meta package
in order to avoid a "bad release". That version causes nearly all of our builds to
fail (anything on analyzer < 5).
So restricting the version range to <1.10.0 works around the issue until we
can upgrade to analyzer 5.
For more info, visit `#lang-dart` in Slack.
[_Created by Sourcegraph batch change `Workiva/avoid_meta_1_10_0`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/avoid_meta_1_10_0)

Avoid meta 1.10.0 problem by unblocking analyzer 5

---

.github/workflows/dart_ci.yml
lib/src/lifecycle_module.dart

In dart 2.19 mocks can no longer handle calls into these private members.
Wrap calls into _parentContext in a try...catch to handle this gracefully.

Avoid accessing private members of child modules

---

example/pubspec.yaml

This PR raises the max allowed versions for react and w_flux. A second batch will follow to raise the minimums of these later.
These versions have been tested across the frontend ecosystem in a test batch prior to releasing these versions.
Feel free to review, approve and merge if CI passes. Otherwise someone on FEDX will come around and get it merged.
[_Created by Sourcegraph batch change `Workiva/react_flux_majors`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/react_flux_majors)

Allow react 7 and w_flux 3

---

example/pubspec.yaml

This PR raises the minimum versions for react and w_flux ensuring that these versions are used everywhere.
Feel free to review, approve and merge if CI passes. Otherwise someone on FEDX will come around and get it merged.
[_Created by Sourcegraph batch change `Workiva/react_flux_majors_2`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/react_flux_majors_2)

react 7 and w_flux 3 step 2

---

example/web/panel/modules/data_load_async_module.dart
example/web/panel/modules/flux_module.dart
example/web/panel/modules/hierarchy_module.dart
example/web/panel/modules/panel_module.dart
example/web/panel/modules/reject_module.dart
example/web/random_color/random_color.dart

Runs a codemod to convert w_flux Action to ActionV2. This is being done in preparation for null-safety.
More information can be found in the `w_flux_codemod` [README.md](https://github.com/Workiva/w_flux/blob/master/w_flux_codemod/README.md).
Contact `#support-frontend-dx` slack channel with any additional questions.
[_Created by Sourcegraph batch change `Workiva/w_flux_action_migration`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/w_flux_action_migration)

w_flux Migration: Action class to ActionV2

---

lib/src/lifecycle_module.dart

I discovered that tests in DPC were failing when I adjusted the timing of module load. 
The cause:
Child module was loaded.
Parent module was unloaded. Clearing the _childModules list.
onWillLoadChildModule completes allowing the child module to enter the _childModules list.
Parent module disposes triggering child module dispose. 
Child module dispose triggers child module unload, which explodes due to disposed stream controllers.
Continue clearing out the child module list until it is empty. 
[contributing-review-types]: …

Ensure all child modules get unloaded

---

lib/src/lifecycle_module.dart

Revert "Ensure all child modules get unloaded"

---

pubspec.yaml

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.4...Workiva:release_w_module_3.0.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.4...3.0.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=242)

RM-244126 Release w_module 3.0.5

---

CHANGELOG.md
lib/src/lifecycle_module.dart
test/lifecycle_module_test.dart

When a child module is loaded, it is possible for the unload of the parent to complete before the onWillLoadChildModule handler executes. 
This is a second attempt at a safe implementation of https://github.com/Workiva/w_module/pull/239.
Check unloading/unloaded and just dispose in that handler instead.
Fix bug where child module loads during the unload of the parent causing Bad State exceptions.
[contributing-manual-testing]: …

Dispose modules during onLoad if parent is unloaded/unloading

---

example/pubspec.yaml

This PR widens the allowable version ranges to over_react 5.0.0 / over_react_test 3.0.0 so that all repos at Workiva can consume without updating all repositories in lock step.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - and **have already been tested and verified as safe for consumption** using the `w_module` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
---
For more information about these changes, see [this …

Allow consumption of null-safe over_react and over_react_test versions

---

example/pubspec.yaml

This PR sets the lower bound of over_react to `^5.0.0` and over_react_test to `^3.0.0` so that all repos at Workiva 
are consuming the null-safe versions of these packages.
These major versions are a critical step towards unlocking null safety in Workiva's Dart ecosystem - 
and **have already been tested and verified as safe for consumption** using the 
`w_module` test PR [listed in this SourceGraph batch](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/over_react_5_test).
Due to the exhaustive consumption testing already performed in this repository by the FED team prior to 
releasing over_react 5.0.0, **these changes can be merged without approval from a FED team member.**
For more information about these changes, see [this …

Consume null-safe over_react v5 and over_react_test v3

---

pubspec.yaml

* [Allow consumption of null-safe over_react and over_react_test versions](https://github.com/Workiva/w_module/pull/245)
* [Consume null-safe over_react v5 and over_react_test v3](https://github.com/Workiva/w_module/pull/246)
Requested by: @aaronlademann-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.6...Workiva:release_w_module_3.0.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.6...3.0.7
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434 …

RM-244775 Release w_module 3.0.7

---

lib/src/lifecycle_module.dart

https://dart.dev/tools/linter-rules/prefer_void_to_null
Change Future<null> to Future<void>

FEA-3688 Update onResume type

---

build.yaml
pubspec.yaml
test/lifecycle_module_test.dart

In order to help with build times and ease null safety migration, we've opted to replace mockito with mocktail. This batch runs the codemod to swap things out, but may require manual intervention.
FEDX will come around and fix things up unless you beat us to it. Once CI is green and the PR is not in draft, you can review and merge it.
[_Created by Sourcegraph batch change `Workiva/mocktail`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/mocktail)

Replace mockito with mocktail

---

example/pubspec.yaml

This PR raises the max version of build_web_compilers to 5.0.0 to prep for Dart 3. 
Since we're all on Dart 2.19 right now, no pub resolution will change as we can't
actually resolve to build_web_compilers 4+ without Dart 3.
Passing CI should be sufficient for QA, so feel free to review and merge this once CI completes.
For more info, reach out to `$support-frontend-dx` on Slack.
[_Created by Sourcegraph batch change `Workiva/build_web_compilers_raise_max_v5_0_0`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/build_web_compilers_raise_max_v5_0_0)

Raise the build_web_compilers dependency max to v5.0.0

---

example/pubspec.yaml
pubspec.yaml

This PR raises the min version of meta to 1.16.0. Passing CI
should be sufficient for QA, so feel free to review and merge this once CI completes.
[_Created by Sourcegraph batch change `Workiva/meta_raise_min_v1_16_0_really`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/meta_raise_min_v1_16_0_really)

Raise the meta dependency min to v1.16.0

---

lib/src/lifecycle_module.dart
lib/w_module.dart
test/lifecycle_module_test.dart

We recently had a scenario where a change to a module prevented it from completing its unload/dispose lifecycle hook. As a result, any parent module using that child module would hang while unloading/disposing. Due to us not handling that well (which has since been fixed), this also resulted in our experience manager not being able to reopen such an experience due to it never fully closing.
- Adds a timeout to the unload step of each child module of 30 seconds. This should be more than enough time to perform an unload; in reality, it should never be close to this timeout.
- When the timeout is hit, we log a warning so that we can identify which module is hanging and so we can setup alerts/queries to know when this is happening.
- When the timeout is hit, we also stop waiting for that …

FEA-7213: Log a warning and skip if child module takes too long to unload

---

pubspec.yaml

* [FEA-7213: Log a warning and skip if child module takes too long to unload](https://github.com/Workiva/w_module/pull/262)
Requested by: @alanknight-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_module/compare/3.0.8...Workiva:release_w_module_3.0.9
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_module/compare/3.0.8...3.0.9
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/5434157055082496/?repo_name=Workiva%2Fw_module&pull_number=263)

RM-302028 Release w_module 3.0.9

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
dart_dependency_validator.yaml
pubspec.yaml

Release CI is failing due to missing CHANGELOG entries. There is a check in gha-dart-oss which prevents this, but its in a more recent version
This PR updates w_module to use the latest gha-dart-oss to implement the check to catch the release errors before the release PR is merged

FEDX-2835: Fixed issues from release

---

example/pubspec.yaml
example/web/panel/index.html
example/web/random_color/index.html

This PR updates all references to React JS files from the React 17 to [React 18 versions](https://github.com/Workiva/react-dart?tab=readme-ov-file#react-18) which will cause most tests and example apps to run on React 18.

Rollout React 18 to tests and example apps
